"""Import public DanFish SEO pages listed in the site's sitemap."""

from __future__ import annotations

import html
import json
import re
import urllib.request
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITEMAP_URL = "https://fish.danmap.co.kr/sitemap.xml"
SOURCE_URL = "https://fish.danmap.co.kr/"
FACT_RE = re.compile(r"<dt>([^<]+)</dt><dd>(.*?)</dd>", re.S)
TEXT_RE = re.compile(r"<[^>]+>")
DESCRIPTION_RE = re.compile(r'<meta name="description" content="([^"]*)"', re.I)


def get(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(request, timeout=20) as response:
        return response.read().decode("utf-8", errors="replace")


def text(value: str) -> str:
    return " ".join(html.unescape(TEXT_RE.sub(" ", value)).split())


def classify_region(lat: float, lng: float) -> str:
    if lat < 33.7:
        return "제주"
    if lat < 35.5:
        return "남해"
    if lng >= 128.2:
        return "동해"
    return "서해"


def parse_page(url: str) -> dict | None:
    page = get(url)
    facts = {text(key): text(value) for key, value in FACT_RE.findall(page)}
    spot_type = facts.get("유형", "")
    if not any(token in spot_type for token in ("갯바위", "방파제", "항구", "선착장", "해변")):
        return None
    coords = re.search(r"(-?\d+\.\d+)\s*,\s*(-?\d+\.\d+)", facts.get("좌표", ""))
    if not coords:
        return None
    lat, lng = map(float, coords.groups())
    point_id = re.search(r"/spots/(\d+)\.html", url).group(1)
    description_match = DESCRIPTION_RE.search(page)
    description = html.unescape(description_match.group(1)).strip() if description_match else ""
    fish = list(dict.fromkeys(item.strip() for item in facts.get("주요 어종", "").split(",") if item.strip()))
    area_parts = [facts.get("행정구역", ""), facts.get("지역", "")]
    return {
        "id": f"danfish-{point_id}",
        "name": facts.get("포인트명", f"DanFish 포인트 {point_id}"),
        "region": classify_region(lat, lng),
        "area": " · ".join(part for part in area_parts if part) or "상세 위치는 원문 확인",
        "lat": lat,
        "lng": lng,
        "difficulty": "현장 확인",
        "level": "medium",
        "fish": fish,
        "type": spot_type,
        "season": "현지 확인",
        "tide": "현지 확인",
        "desc": description or "DanFish에서 수집한 위치 기반 바다낚시 포인트입니다.",
        "tip": "출조 전 원문과 현장 안내를 확인하세요. 출입 제한, 기상, 물때는 수시로 달라질 수 있습니다.",
        "source": "DanFish",
        "sourceCode": point_id,
        "checkedAt": "2026-06-02",
        "sources": [{"label": "DanFish 원문", "url": url}],
        "catalog": True,
        "catalogName": "DanFish",
        "depth": facts.get("수심", ""),
        "bottom": facts.get("바닥 재질", ""),
    }


def main() -> None:
    sitemap = ET.fromstring(get(SITEMAP_URL))
    urls = [
        node.text
        for node in sitemap.findall("{http://www.sitemaps.org/schemas/sitemap/0.9}url/{http://www.sitemaps.org/schemas/sitemap/0.9}loc")
        if node.text and "/spots/" in node.text
    ]
    points = []
    errors = []
    with ThreadPoolExecutor(max_workers=8) as executor:
        futures = {executor.submit(parse_page, url): url for url in urls}
        for index, future in enumerate(as_completed(futures), 1):
            try:
                point = future.result()
                if point:
                    points.append(point)
            except Exception as error:  # noqa: BLE001
                errors.append((futures[future], str(error)))
            if index % 200 == 0:
                print(f"checked {index}/{len(urls)}")

    points.sort(key=lambda point: (point["region"], point["name"], point["id"]))
    output = (
        "// Generated by tools/import-danfish.py from public DanFish SEO pages.\n"
        f"// Source: {SOURCE_URL} (checked 2026-06-02)\n"
        f"const danfishFishingSpots = {json.dumps(points, ensure_ascii=False, indent=2)};\n"
    )
    (ROOT / "danfish-spots.js").write_text(output, encoding="utf-8")
    print(f"wrote {len(points)} sea points; errors={len(errors)}")


if __name__ == "__main__":
    main()
