import json
import re
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "data" / "osm-freshwater-exploration.json"
OUT_JS = ROOT / "osm-freshwater-spots.js"
OVERPASS_URL = "https://overpass-api.de/api/interpreter"
BOUNDS = "33.0,124.0,38.8,130.0"
MAX_SPOTS = 650
TYPE_LIMITS = {"저수지": 380, "호수·강": 80, "하천": 170, "수로": 20}
EXCLUDED = re.compile(r"낚시터|유료|좌대|글램핑|캠핑장|공원|골프|테마|리조트|워터파크")


def fetch_overpass():
    query = f"""
[out:json][timeout:180];
(
  way["natural"="water"]["name"]({BOUNDS});
  relation["natural"="water"]["name"]({BOUNDS});
  way["waterway"~"river|stream|canal"]["name"]({BOUNDS});
  relation["waterway"~"river|stream|canal"]["name"]({BOUNDS});
);
out center tags;
"""
    data = urlencode({"data": query}).encode("utf-8")
    request = Request(
        OVERPASS_URL,
        data=data,
        headers={"User-Agent": "moolttae-map/1.0", "Content-Type": "application/x-www-form-urlencoded"},
    )
    with urlopen(request, timeout=240) as response:
        return json.load(response)


def get_region(lat, lng):
    if lat < 34.1:
        return "제주권"
    if lat < 36.0 and lng < 128.0:
        return "전라권"
    if lat < 37.0 and lng >= 128.0:
        return "경상권"
    if lat >= 37.0 and lng < 128.0:
        return "수도권"
    if lat >= 37.0:
        return "강원권"
    return "충청권"


def get_type(tags):
    waterway = tags.get("waterway")
    if waterway == "canal":
        return "수로"
    if waterway in {"river", "stream"}:
        return "하천"
    if tags.get("water") == "reservoir":
        return "저수지"
    return "호수·강"


def get_coordinates(element):
    center = element.get("center", element)
    return center.get("lat"), center.get("lon")


def normalize_name(name):
    return re.sub(r"\s+", "", name).lower()


def build_spots(payload):
    spots = []
    seen = set()
    for element in payload.get("elements", []):
        tags = element.get("tags", {})
        name = tags.get("name:ko") or tags.get("name")
        lat, lng = get_coordinates(element)
        if not name or lat is None or lng is None or EXCLUDED.search(name):
            continue
        if not (33 <= lat <= 38.8 and 124 <= lng <= 130):
            continue

        # Keep same-name waters in different districts, while collapsing OSM segments.
        key = (normalize_name(name), round(lat, 1), round(lng, 1), get_type(tags))
        if key in seen:
            continue
        seen.add(key)
        spots.append(
            {
                "id": f"osm-fresh-{element['type']}-{element['id']}",
                "name": name,
                "region": get_region(lat, lng),
                "area": "OSM 이름 있는 자연 수역",
                "lat": lat,
                "lng": lng,
                "level": "medium",
                "fish": [],
                "type": get_type(tags),
                "season": "현장 확인",
                "tide": "수역 탐색 기준점",
                "coordinateConfidence": "수역 탐색 기준점 · OSM 이름 있는 수역 좌표",
                "desc": "OpenStreetMap에서 명칭과 좌표가 확인된 자연 수역 탐색 후보입니다.",
                "tip": "낚시 조황과 연안 진입로는 아직 교차 확인 전입니다. 상세 지도와 현장 표지판을 먼저 확인하세요.",
                "warning": "탐색 후보입니다. 낚시 가능 여부, 출입 제한, 사유지, 수위와 금지 구역을 현장에서 확인하세요.",
                "freshwater": True,
                "discovery": True,
                "osmType": tags.get("waterway") or tags.get("water") or tags.get("natural") or "water",
                "sources": [
                    {
                        "label": "OpenStreetMap 수역 확인",
                        "url": f"https://www.openstreetmap.org/{element['type']}/{element['id']}",
                    }
                ],
            }
        )

    selected = []
    for spot_type, limit in TYPE_LIMITS.items():
        pool = [item for item in spots if item["type"] == spot_type]
        pool.sort(key=lambda item: (item["region"], item["name"], item["id"]))
        by_region = {}
        for item in pool:
            by_region.setdefault(item["region"], []).append(item)
        while len(selected) < MAX_SPOTS and limit > 0 and any(by_region.values()):
            for region in sorted(by_region):
                if by_region[region] and limit > 0:
                    selected.append(by_region[region].pop(0))
                    limit -= 1

    return selected[:MAX_SPOTS]


def main():
    spots = build_spots(fetch_overpass())
    OUT_JSON.parent.mkdir(exist_ok=True)
    OUT_JSON.write_text(json.dumps(spots, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    OUT_JS.write_text(
        "// Generated by tools/import-osm-freshwater.py. Do not edit manually.\n"
        f"const osmFreshwaterExplorationSpots = {json.dumps(spots, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(spots)} OSM freshwater exploration spots")


if __name__ == "__main__":
    main()
